# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
   include:
    - master
    - develop

steps:
- script: echo Starting Unity build!
  displayName: 'Announce build'

- script: '%UNITY_EDITOR_PATH% -batchmode
  -projectPath $(Repository.LocalPath)/src
  -buildWindows64Player $(build.artifactstagingdirectory)/$(player.executableName).exe
  -quit'
  displayName: "Build unity for windows 64 platform"

- task: PublishBuildArtifacts@1