# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
   include:
    - master
    - develop

pool: 'default'

steps:
- script: echo Starting Unity build!
  displayName: 'Announce build'

- task: UnityBuildTask@2
  inputs:
    buildTarget: 'standalone'
    unityProjectPath: ./src
    buildScenes: 'LSDScene'

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'