#!/bin/sh
#

BRANCH_NAME=$(git symbolic-ref HEAD | egrep -o '([a-z0-9.-]+\/[a-z0-9.-]+)$')

# Regex patterns
FEATURE_BUGFIX_PATTERN="^\(feature\|bugfix\)\/#[0-9]\{1,3\}[a-z-]\{10,\}$"
RELEASE_PATTERN="^release\/[0-9]\{1,2\}\.[0-9]\{1,2\}$"

# Colors
RED='\033[1;31m'
CYAN='\033[1;36m'
NO_COLOR='\033[0m'

if !(
  grep -q -o $FEATURE_BUGFIX_PATTERN <<< $BRANCH_NAME ||
  grep -q -o $RELEASE_PATTERN <<< $BRANCH_NAME
) ; then
  printf $RED
  printf "\n\t ############################"
  printf "\n\t ####  Bad branch name!  ####"
  printf "\n\t ############################"
  printf $NO_COLOR
  printf "\n"
  printf "\n\t - Branch name should follow git flow rules"
  printf "\n\t - Feature branch should have issue number after forward slash (/)"
  printf "\n\t - Should be at least 20 characters long"
  printf "\n"
  printf "\n"
  printf $CYAN
  printf "\n\t Examples:"
  printf $NO_COLOR
  printf "\n"
  printf "\n\t - feature/#99-my-feature-branch"
  printf "\n\t - bugfix/#99-my-release-branch"
  printf "\n\t - release/0.1"
  printf "\n"
  printf "\n"

  # Error
  exit 1
fi

# Success
exit 0